
CREATE TABLE MEMBER(
    USERID VARCHAR2(20) PRIMARY KEY,
    USERPWD VARCHAR2(50) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10) CHECK(GENDER IN('M','F')),
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    ADDRESSS VARCHAR2(200) NOT NULL,
    CHILD_NAME VARCHAR2(20) NOT NULL,
    CHILD_BIRTH DATE NOT NULL,
    CHILD_GENDER VARCHAR2(10) CHECK(CHILD_GENDER IN('M','F')),
    CHILD_CLASS VARCHAR2(20) NOT NULL
);

CREATE TABLE CATEGORY (
       BOARDTYPE NUMBER PRIMARY KEY,
       BOARDNAME VARCHAR2(300) NOT NULL
);

INSERT INTO CATEGORY VALUES(1, '학사일정');
INSERT INTO CATEGORY VALUES(2, '사진게시판');

CREATE TABLE BOARD (
      BNO NUMBER PRIMARY KEY,
      BTYPE NUMBER NOT NULL,
      BTITLE VARCHAR2(500) NOT NULL,
      BCONTENT VARCHAR2(3000) NOT NULL,
      BWRITER VARCHAR2(15) NOT NULL,
      BCOUNT NUMBER DEFAULT 0,
      BOARDFILE VARCHAR2(600),
      BDATE DATE DEFAULT SYSDATE,
      STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
      CONSTRAINT FK_BTYPE FOREIGN KEY(BTYPE) REFERENCES CATEGORY(BOARDTYPE),
      CONSTRAINT FK_BWRITER FOREIGN KEY(BWRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL
);




