

CREATE TABLE MEMBER(
    USERID VARCHAR2(20) PRIMARY KEY,
    USERPWD VARCHAR2(50) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10) CHECK(GENDER IN('M','F')),
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    ADDRESSS VARCHAR2(200) NOT NULL,
    CHILD_NAME VARCHAR2(20) NOT NULL,
    CHILD_BIRTH DATE NOT NULL,
    CHILD_GENDER VARCHAR2(10) CHECK(CHILD_GENDER IN('M','F')),
    CHILD_CLASS VARCHAR2(20) NOT NULL
);

CREATE TABLE CATEGORY (
       BOARDTYPE NUMBER PRIMARY KEY,
       BOARDNAME VARCHAR2(300) NOT NULL
);

INSERT INTO CATEGORY VALUES(1, '학사일정');
INSERT INTO CATEGORY VALUES(2, '사진게시판');

CREATE TABLE BOARD (
      BNO NUMBER PRIMARY KEY,
      BTYPE NUMBER NOT NULL,
      BTITLE VARCHAR2(500) NOT NULL,
      BCONTENT VARCHAR2(3000) NOT NULL,
      BWRITER VARCHAR2(15) NOT NULL,
      BCOUNT NUMBER DEFAULT 0,
      BOARDFILE VARCHAR2(600),
      BDATE DATE DEFAULT SYSDATE,
      STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
      CONSTRAINT FK_BTYPE FOREIGN KEY(BTYPE) REFERENCES CATEGORY(BOARDTYPE),
      CONSTRAINT FK_BWRITER FOREIGN KEY(BWRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL
);

CREATE TABLE CLASS_KIND (
    CLASS_CODE NUMBER PRIMARY KEY,
    CLASS_NAME VARCHAR2(20) NOT NULL,
    TEACHER_CODE NUMBER NOT NULL UNIQUE,
    MAX_ENTRANCE NUMBER DEFAULT 20 NOT NULL,
    LIMIT_AGE NUMBER NOT NULL
);

CREATE TABLE TEACHER (
    TEACHER_CODE NUMBER PRIMARY KEY,
    TEACHER_NAME VARCHAR2(20) NOT NULL,
    TEACHER_JOB_CODE NUMBER NOT NULL,
    TEACHER_NO VARCHAR2(30) NOT NULL,
    TEACHER_GENDER VARCHAR2(10) CHECK (TEACHER_GENDER IN ('M','F')),
    TEACHER_PHONE VARCHAR2(20) NOT NULL,
    TEACHER_EMAIL VARCHAR2(50) NOT NULL,
    TEACHER_ADDR VARCHAR2(100) NOT NULL,
    PROFILE_PATH VARCHAR2(100),
    HIRE_DATE DATE NOT NULL,
    ENT_DATE DATE,
    ENT_YN VARCHAR2(10) CHECK (ENT_YN IN ('Y','N')),
    CLASS_CODE NUMBER NOT NULL,
    HOBONG NUMBER,
    CONSTRAINT FK_TCH_CLS FOREIGN KEY(CLASS_CODE) REFERENCES CLASS_KIND(CLASS_CODE)
);





















